### ISSUE TITLE
Criar tela - Início

### ISSUE THREAD

**Issue by rannaraabe** [rannaraabe/blood#1]
**Desenvolver:**
- Tela Início

**Descrição:**

Tela de início exibe a opção de fazer login com o Google "Comece aqui". Caso seja a primeira vez o usuário faz login no aplicativo, o aplicativo redireciona para a Tela de cadastro para que o usuário informe os demais dados; caso não seja a primeira vez que o usuário faz login, o aplicativo realiza o login com Google e redireciona para a Tela de feed. 

**Protótipo:**

![image](https://user-images.githubusercontent.com/27364629/150351119-c42802e9-0985-4909-a48b-05fac64bc510.png)

**Comment by camiladuartes** [comment]
Tela feita. Faltando apenas ajustar fonte e imagem da gota de sangue.

**Comment by rannaraabe** [comment]
> Tela feita. Faltando apenas ajustar fonte e imagem da gota de sangue.

Feito.
